/*
 * <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< PORT_config.h >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
 *
 *  Created on: Oct 5, 2026
 *  Author: Ali Osama Ismail
 *  Layer : MCAL
 *  SWC   : PORT
 *
 *
 */

#ifndef PORT_CONFIG_H_
#define PORT_CONFIG_H_

#define DIO_INPUT  0
#define DIO_OUTPUT 1

#define PORTA_PIN0_DIR DIO_OUTPUT
#define PORTA_PIN1_DIR DIO_OUTPUT
#define PORTA_PIN2_DIR DIO_OUTPUT
#define PORTA_PIN3_DIR DIO_OUTPUT
#define PORTA_PIN4_DIR DIO_INPUT
#define PORTA_PIN5_DIR DIO_INPUT
#define PORTA_PIN6_DIR DIO_INPUT
#define PORTA_PIN7_DIR DIO_INPUT


#define PORTB_PIN0_DIR DIO_INPUT
#define PORTB_PIN1_DIR DIO_INPUT
#define PORTB_PIN2_DIR DIO_INPUT
#define PORTB_PIN3_DIR DIO_INPUT
#define PORTB_PIN4_DIR DIO_INPUT
#define PORTB_PIN5_DIR DIO_INPUT
#define PORTB_PIN6_DIR DIO_INPUT
#define PORTB_PIN7_DIR DIO_INPUT

#define PORTC_PIN0_DIR DIO_INPUT
#define PORTC_PIN1_DIR DIO_INPUT
#define PORTC_PIN2_DIR DIO_INPUT
#define PORTC_PIN3_DIR DIO_INPUT
#define PORTC_PIN4_DIR DIO_INPUT
#define PORTC_PIN5_DIR DIO_INPUT
#define PORTC_PIN6_DIR DIO_INPUT
#define PORTC_PIN7_DIR DIO_INPUT

#define PORTD_PIN0_DIR DIO_INPUT
#define PORTD_PIN1_DIR DIO_INPUT
#define PORTD_PIN2_DIR DIO_INPUT
#define PORTD_PIN3_DIR DIO_INPUT
#define PORTD_PIN4_DIR DIO_INPUT
#define PORTD_PIN5_DIR DIO_INPUT
#define PORTD_PIN6_DIR DIO_INPUT
#define PORTD_PIN7_DIR DIO_INPUT


//initial value

#define INPUT_FLOATING 0
#define INPUT_PULL_UP  1

#define OUTPUT_LOW     0
#define OUTPUT_HIGH    1


#define PORTA_PIN0_VALUE OUTPUT_HIGH
#define PORTA_PIN1_VALUE OUTPUT_LOW
#define PORTA_PIN2_VALUE OUTPUT_HIGH
#define PORTA_PIN3_VALUE OUTPUT_LOW
#define PORTA_PIN4_VALUE INPUT_FLOATING
#define PORTA_PIN5_VALUE INPUT_FLOATING
#define PORTA_PIN6_VALUE INPUT_FLOATING
#define PORTA_PIN7_VALUE INPUT_FLOATING


#define PORTB_PIN0_VALUE INPUT_FLOATING
#define PORTB_PIN1_VALUE INPUT_FLOATING
#define PORTB_PIN2_VALUE INPUT_FLOATING
#define PORTB_PIN3_VALUE INPUT_FLOATING
#define PORTB_PIN4_VALUE INPUT_FLOATING
#define PORTB_PIN5_VALUE INPUT_FLOATING
#define PORTB_PIN6_VALUE INPUT_FLOATING
#define PORTB_PIN7_VALUE INPUT_FLOATING

#define PORTC_PIN0_VALUE INPUT_FLOATING
#define PORTC_PIN1_VALUE INPUT_FLOATING
#define PORTC_PIN2_VALUE INPUT_FLOATING
#define PORTC_PIN3_VALUE INPUT_FLOATING
#define PORTC_PIN4_VALUE INPUT_FLOATING
#define PORTC_PIN5_VALUE INPUT_FLOATING
#define PORTC_PIN6_VALUE INPUT_FLOATING
#define PORTC_PIN7_VALUE INPUT_FLOATING

#define PORTD_PIN0_VALUE INPUT_FLOATING
#define PORTD_PIN1_VALUE INPUT_FLOATING
#define PORTD_PIN2_VALUE INPUT_FLOATING
#define PORTD_PIN3_VALUE INPUT_FLOATING
#define PORTD_PIN4_VALUE INPUT_FLOATING
#define PORTD_PIN5_VALUE INPUT_FLOATING
#define PORTD_PIN6_VALUE INPUT_FLOATING
#define PORTD_PIN7_VALUE INPUT_FLOATING



#endif /* PORT_CONFIG_H_ */
